version: '3.7'

services:
  mongo:
    image: mongo

    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - qualime

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    volumes:
      - qualime_db_mongo:/data/db

  mongo-express:
    image: mongo-express

    restart: unless-stopped

    ports:
      - ${ME_CONFIG_PORT}:${ME_CONFIG_PORT}

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}

    depends_on:
      - mongo

    networks:
      - qualime

  api:
    build:
      context: ./dockerfiles/api

    image: qualime/api

    container_name: qualime-api

    volumes:
      - ./api:/api
      - ./entrypoints/entrypoint-api.sh:/api/entrypoint-api.sh

    working_dir: /api

    ports:
      - ${API_PORT}:${API_PORT}

    environment:
      API_PORT: ${API_PORT}
      REACT_APP_API_DOMAIN: ${REACT_APP_API_DOMAIN}
      MONGO_PORT: ${MONGO_PORT}

    command: ./entrypoint-api.sh

    networks:
      - qualime

  app:
    build:
      context: ./dockerfiles/app

    image: qualime/app

    container_name: qualime-app

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/qualime.com.br/fullchain.pem:/etc/letsencrypt/live/qualime.com.br/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/qualime.com.br/privkey.pem:/etc/letsencrypt/live/qualime.com.br/privkey.pem

    working_dir: /usr/share/nginx/html

    ports:
      - ${REACT_APP_PORT}:80
      - ${REACT_APP_SSL_PORT}:443

    networks:
      - qualime

volumes:
  qualime_db_mongo:

networks:
  qualime:
    driver: bridge